- name: Create folder for docker-compose files.
  ansible.builtin.file:
    path: "~/docker-compose/healthchecks"
    state: directory
    recurse: true
    mode: "0700"

- name: Generate config file.
  ansible.builtin.template:
    src: local_settings.py
    dest: ~/docker-compose/healthchecks/local_settings.py
    mode: "0700"
  notify:
    - Restart healthchecks.
    - Restart frontend.

- name: Generate docker-compose file.
  ansible.builtin.template:
    src: docker-compose.yml
    dest: ~/docker-compose/healthchecks/docker-compose.yml
    mode: "0700"
  notify:
    - Restart frontend.

- name: Start containers.
  community.docker.docker_compose:
    project_src: "~/docker-compose/healthchecks"
    pull: true
    build: true
