- name: Create btrfs subvolumes.
  btrfs_subvolume:
    path: /home/healthchecks/volumes/{{ subvolume }}
    state: present
    owner: healthchecks
    group: healthchecks
  loop:
    - db
    - app
  loop_control:
    loop_var: subvolume

- name: Generate healthchecks config.
  ansible.builtin.template:
    src: local_settings.py
    dest: /home/healthchecks/volumes/app/local_settings.py
    owner: healthchecks
    group: healthchecks
    mode: 0600

- name: Create pod.
  become: true
  become_user: "healthchecks"
  containers.podman.podman_pod:
    name: healthchecks
    state: started

- name: Create db container.
  become: true
  become_user: "healthchecks"
  containers.podman.podman_container:
    name: db
    image: "docker.io/postgres:14"
    image_strict: true
    restart_policy: always
    pod: healthchecks
    log_driver: "k8s-file"
    env:
      POSTGRES_PASSWORD: "{{ healthchecks_db_password }}"
      POSTGRES_USER: hc
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hc
    volumes:
      - "/home/healthchecks/volumes/db:/var/lib/postgresql/data:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
    healthcheck: "pg_isready -U {{ healthchecks_db_user }} -d {{ healthchecks_db_name }}"
    healthcheck_interval: 30s
    healthcheck_retries: 3
    healthcheck_start_period: 10s
    healthcheck_timeout: 30s

- name: Create app container.
  become: true
  become_user: healthchecks
  containers.podman.podman_container:
    name: app
    image: docker.io/linuxserver/healthchecks:2.3.20220812
    image_strict: true
    pod: healthchecks
    restart_policy: always
    requires: db
    log_driver: "k8s-file"
    env:
      SUPERUSER_EMAIL: "{{ healthchecks_admin_email }}"
      SUPERUSER_PASSWORD: "{{ healthchecks_admin_password }}"
      REGENERATE_SETTINGS: "False"
    volumes:
      - "/home/healthchecks/volumes/app/:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
