- name: Create folder for docker-compose files.
  ansible.builtin.file:
    path: "~/docker-compose/paperless"
    state: directory
    recurse: true
    mode: "0700"

- name: Generate docker-compose file.
  ansible.builtin.template:
    src: docker-compose.yml
    dest: ~/docker-compose/paperless/docker-compose.yml
    mode: "0600"

- name: Start containers.
  community.docker.docker_compose:
    project_src: "~/docker-compose/paperless"
    pull: true

- name: Allow HTTP over tailscale.
  community.general.ufw:
    rule: allow
    port: 8002
    proto: "tcp"
    interface: tailscale0
    direction: in
