- hosts: vps
  become: true
  vars_files:
    - secrets.yml
  pre_tasks:
    - name: Set hostname.
      ansible.builtin.hostname:
        name: vps
    - name: Update pacman cache.
      community.general.pacman:
        update_cache: true
  tasks:
    - name: Import roles.
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - timezone
        - ssh
        - firewall
        - haveged
        - docker
        - nextcloud
        - paperless
        - adguard
