- hosts: vps
  become: true
  vars_files:
    - secrets.yml
  pre_tasks:
    - name: Set hostname.
      ansible.builtin.hostname:
        name: vps
    - name: Update pacman cache.
      community.general.pacman:
        update_cache: true
  tasks:
    - name: Basic setup.
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - timezone
        - firewall
        - ssh
        - artis3n.tailscale
    - name: Setup containers.
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - podman
        - healthchecks
        - nextcloud
        - paperless

        # - haveged
        # - cert
        # - dns
        # - frontend
        # - dashboard
        # - uptime
        # - adguard
        # - digikam
