collections:
  - name: community.general
    version: 5.1.1
  - name: community.docker
    version: 2.6.0
  - name: community.healthchecksio
    version: 1.2.0
  - name: community.grafana
    version: 1.4.0
