collections:
  - name: community.general
    version: 5.3.0
  - name: community.docker
    version: 2.7.0
  - name: community.healthchecksio
    version: 1.2.0
  - name: community.grafana
    version: 1.5.0
