collections:
  - name: community.general
    version: 5.4.0
  - name: ansible.posix
    version: 1.4.0
  - name: containers.podman
    version: 1.9.4
roles:
  - name: artis3n.tailscale
    version: v3.2.3
