collections:
  - name: community.general
    version: 5.4.0
  - name: community.docker
    version: 2.7.1
  - name: community.healthchecksio
    version: 1.2.0
  - name: community.grafana
    version: 1.5.1
