collections:
  - name: community.general
    version: 6.1.0
  - name: community.docker
    version: 3.3.1
  - name: community.healthchecksio
    version: 1.2.0
  - name: community.grafana
    version: 1.5.3
