version: "3.9"
services:
  app:
    container_name: audiobookshelf_app
    image: "ghcr.io/advplyr/audiobookshelf:2.1.1"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - config:/config
      - metadata:/metadata
      - audiobooks:/audiobooks
      - podcasts:/podcasts
    networks:
      - frontend
      - default
volumes:
  config:
  metadata:
  audiobooks:
  podcasts:
networks:
  default:
  frontend:
    external: true