- name: Install nginx.
  ansible.builtin.package:
    name: nginx
    state: present

- name: Create site directory.
  ansible.builtin.file:
    path: /etc/nginx/sites
    state: directory

- name: Generate nginx config.
  ansible.builtin.template:
    src: "{{ file }}"
    dest: "/etc/nginx/{{ file }}"
  loop_control:
    loop_var: file
  loop:
    - nginx.conf
    - ssl.conf
    - proxy.conf
  notify:
    - Restart proxy.

- name: Start nginx.
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Allow HTTP(S) over tailscale.
  community.general.ufw:
    rule: allow
    port: "{{ port }}"
    proto: "tcp"
    interface: tailscale0
    direction: in
  loop:
    - 80
    - 443
  loop_control:
    loop_var: port
