- name: Create folder for docker-compose files.
  ansible.builtin.file:
    path: "~/docker-compose/{{ stack }}"
    state: directory
    recurse: true
    mode: "0700"
  loop:
    - headscale
  loop_control:
    loop_var: stack
