- name: Setup A records.
  community.general.cloudflare_dns:
    domain: "{{ domain }}"
    record: "{{ subdomain }}"
    type: A
    state: present
    value: "207.180.226.248"
    account_api_key: "{{ cloudflare_api_key }}"
    account_email: "{{ cloudflare_email }}"
  loop: "{{ ['@', ] + subdomains }}"
  loop_control:
    loop_var: subdomain

- name: Setup MX records.
  community.general.cloudflare_dns:
    domain: "{{ domain }}"
    record: "@"
    type: MX
    state: present
    value: "{{ record.value }}"
    priority: "{{ record.priority }} "
    account_api_key: "{{ cloudflare_api_key }}"
    account_email: "{{ cloudflare_email }}"
  loop:
    - { "value": "mail.protonmail.ch", "priority": 10 }
    - { "value": "mailsec.protonmail.ch", "priority": 20 }
  loop_control:
    loop_var: record

- name: Setup TXT records.
  community.general.cloudflare_dns:
    domain: "{{ domain }}"
    record: "@"
    type: TXT
    state: present
    value: "{{ record.value }}"
    account_api_key: "{{ cloudflare_api_key }}"
    account_email: "{{ cloudflare_email }}"
  loop:
    - { "record": "@", "value": "google-site-verification=qfIZblxuEnl3V9LzTkjqaDyKY-kKbu3DW2uirfFgp4A" }
    - { "record": "@", "value": "protonmail-verification=4ba64976c225cfcba3ba4364ce8d703a159d0604" }
    - { "record": "@", "value": "v=spf1 include:_spf.protonmail.ch mx ~all" }
    - { "record": "_dmarc", "value": "v=DMARC1; p=none"}
  loop_control:
    loop_var: record

- name: Setup CNAME records.
  community.general.cloudflare_dns:
    domain: "{{ domain }}"
    record: "{{ record.record }}"
    type: CNAME
    state: present
    value: "{{ record.value }}"
    account_api_key: "{{ cloudflare_api_key }}"
    account_email: "{{ cloudflare_email }}"
  loop:
    - { "record": "protonmail._domainkey", "value": "protonmail.domainkey.d6qobjpxh7q5uez3ilvagnjmekgvmblrx6k2l4kgfmn5m4jt6mikq.domains.proton.ch" }
    - { "record": "protonmail2._domainkey", "value": "protonmail2.domainkey.d6qobjpxh7q5uez3ilvagnjmekgvmblrx6k2l4kgfmn5m4jt6mikq.domains.proton.ch" }
    - { "record": "protonmail3._domainkey", "value": "protonmail3.domainkey.d6qobjpxh7q5uez3ilvagnjmekgvmblrx6k2l4kgfmn5m4jt6mikq.domains.proton.ch" }
  loop_control:
    loop_var: record