version: "3.9"
services:
  cache:
    container_name: paperless_cache
    image: redis:7.2.4-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli --raw incr ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - cache:/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
  db:
    container_name: paperless_db
    image: postgres:15.3
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U paperless" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: "{{ paperless.db.password }}"
  app:
    container_name: paperless_app
    image: ghcr.io/paperless-ngx/paperless-ngx:2.4.1
    restart: unless-stopped
    depends_on:
      - db
      - cache
      - gotenberg
      - tika
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - app_data:/usr/src/paperless/data
      - app_media:/usr/src/paperless/media
      - app_export:/usr/src/paperless/export
      - app_consume:/usr/src/paperless/consume
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
    environment:
      PAPERLESS_REDIS: redis://cache:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_OCR_LANGUAGES: "deu eng"
      PAPERLESS_OCR_LANGUAGE: "deu"
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_SECRET_KEY: "{{ paperless.secret }}"
      PAPERLESS_DBPASS: "{{ paperless.db.password }}"
      PAPERLESS_ADMIN_USER: "{{ paperless.admin.user }}"
      PAPERLESS_ADMIN_PASSWORD: "{{ paperless.admin.password }}"
      PAPERLESS_URL: "https://paperless.vps.fkoehler.org"
      PAPERLESS_TASK_WORKERS: "4"
    ports:
      - "8002:8000/tcp"

  gotenberg:
    container_name: paperless_gotenberg
    image: gotenberg/gotenberg:8.0.2
    restart: unless-stopped
    environment:
      CHROMIUM_DISABLE_ROUTES: 1
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"

  tika:
    container_name: paperless_tika
    image: apache/tika:2.5.0-full
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"

  protonmail:
    container_name: paperless_protonmail
    image: shenxn/protonmail-bridge:3.5.4-1
    # build: ./protonmail/deb
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - "protonmail:/root"

volumes:
  app_data:
  app_media:
  app_consume:
  app_export:
  db:
  cache:
  protonmail:
