- name: Install OpenSSH.
  ansible.builtin.package:
    name: openssh
    state: present

- name: Start OpenSSH.
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true

- name: Configure OpenSSH server.
  ansible.builtin.template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  notify: Restart sshd.

- name: Block standard SSH port.
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    service: ssh
    state: disabled
    zone: public

- name: Open custom SSH port.
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    port: "{{ ssh_port }}/tcp"
    state: enabled
    zone: public

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers
