- name: Create btrfs subvolumes.
  btrfs_subvolume:
    path: /home/nextcloud/volumes/{{ subvolume }}
    state: present
    owner: nextcloud
    group: nextcloud
  loop:
    - db
    - app
  loop_control:
    loop_var: subvolume

- name: Create pod.
  become: true
  become_user: "nextcloud"
  containers.podman.podman_pod:
    name: nextcloud
    state: started

- name: Create db container.
  become: true
  become_user: "nextcloud"
  containers.podman.podman_container:
    name: db
    image: "docker.io/postgres:14"
    image_strict: true
    restart_policy: always
    pod: nextcloud
    log_driver: "k8s-file"
    env:
      POSTGRES_PASSWORD: "{{ nextcloud_db_password }}"
      POSTGRES_USER: "{{ nextcloud_db_user }}"
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: "{{ nextcloud_db_name }}"
    volumes:
      - "/home/nextcloud/volumes/db:/var/lib/postgresql/data:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
    healthcheck: "pg_isready -U {{ healthchecks_db_user }} -d {{ healthchecks_db_name }} "
    healthcheck_interval: 30s
    healthcheck_retries: 3
    healthcheck_start_period: 10s
    healthcheck_timeout: 30s

- name: Create app container.
  become: true
  become_user: nextcloud
  containers.podman.podman_container:
    name: app
    image: "docker.io/nextcloud:24-apache"
    image_strict: true
    requires: db
    restart_policy: always
    pod: nextcloud
    log_driver: "k8s-file"
    env:
      POSTGRES_PASSWORD: "{{ nextcloud_db_password }}"
      POSTGRES_USER: "{{ nextcloud_db_user }}"
      POSTGRES_DB: "{{ nextcloud_db_name }}"
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.svc.fkoehler.xyz nextcloud_app"
      OVERWRITEHOST: "nextcloud.svc.fkoehler.xyz"
      OVERWRITEPROTOCOL: "https"
    volumes:
      - "/home/nextcloud/volumes/app:/var/www/html:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"

- name: Create cron container.
  become: true
  become_user: nextcloud
  containers.podman.podman_container:
    name: cron
    image: "docker.io/nextcloud:24-apache"
    image_strict: true
    requires: app
    restart_policy: always
    pod: nextcloud
    log_driver: "k8s-file"
    entrypoint: /cron.sh
    volumes:
      - "/home/nextcloud/volumes/app:/var/www/html:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
