version: "3.9"
services:
  db:
    container_name: healthchecks_db
    image: "postgres:14"
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: "{{ healthchecks.db.password }}"
      POSTGRES_USER: hc
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hc"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "db:/var/lib/postgresql/data:rw"
      - "/etc/localtime:/etc/localtime:ro"
  app:
    container_name: healthchecks_app
    image: linuxserver/healthchecks:2.2.1
    restart: "unless-stopped"
    depends_on:
      - db
    environment:
      EMAIL_HOST: "{{ bot.email.smtp.host }}"
      EMAIL_PORT: "{{ bot.email.smtp.port }}"
      EMAIL_HOST_USER: "{{ bot.email.address }}"
      EMAIL_HOST_PASSWORD: "{{ bot.email.password }}"
      EMAIL_USE_TLS: "True"
      MATRIX_HOMESERVER: "{{ bot.matrix.homeserver }}"
      MATRIX_USER_ID: "{{ bot.matrix.user }}"
      MATRIX_ACCESS_TOKEN: "{{ bot.matrix.token }}"
      DEBUG: "False"
      DB: "postgres"
      DB_HOST: "healthchecks_db"
      DB_PASSWORD: "{{ healthchecks.db.password }}"
      DB_USER: "hc"
      DB_TABLE: "hc"
      SECRET_KEY: "{{ healthchecks.secret }}"
      SUPERUSER_EMAIL: "{{ healthchecks.admin.email }}"
      SUPERUSER_PASSWORD: "{{ healthchecks.admin.password }}"
      ALLOWED_HOSTS: "[\"{{ healthchecks.allowed_hosts | join('\",\"') }}\"]"
      REGENERATE_SETTINGS: "False"
      SITE_NAME: "{{ healthchecks.site.name }}"
      SITE_ROOT: "{{ healthchecks.site.root }}"
      TZ: "Europe/Berlin"
    volumes:
      - "app:/config"
      - "./local_settings.py:/config/local_settings.py"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - frontend
      - default
volumes:
  db:
  app:
networks:
  default:
  frontend:
    external: true
