- name: Install firewalld.
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Start firewalld.
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
