- name: Install ufw.
  ansible.builtin.package:
    name: ufw
    state: present

- name: Start and enable ufw.
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: true

- name: Enable ufw.
  community.general.ufw:
    state: enabled

- name: Limit public SSH.
  community.general.ufw:
    rule: limit
    port: "{{ ssh_port }}"
    proto: tcp

- name: Limit public HTTPS.
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Allow DNS over tailscale.
  community.general.ufw:
    rule: allow
    port: 53
    proto: "{{ proto }}"
    interface: tailscale0
    direction: in
  loop_control:
    loop_var: proto
  loop:
    - tcp
    - udp

- name: Deny incoming traffic by default.
  community.general.ufw:
    policy: deny
    direction: incoming
