version: "3.9"
services:
  app:
    container_name: adguard_app
    image: "adguard/adguardhome:v0.107.7"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "config:/opt/adguardhome/conf"
      - "work:/opt/adguardhome/work"
    networks:
      - frontend
      - default
    ports:
      - "53:53/tcp"
      - "53:53/udp"
volumes:
  config:
  work:
networks:
  default:
  frontend:
    external: true
