version: "3.9"
services:
  app:
    container_name: adguard_app
    image: "adguard/adguardhome:v0.107.20"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - "config:/opt/adguardhome/conf"
      - "work:/opt/adguardhome/work"
    networks:
      - frontend
      - default
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --timeout 1 --tries 1 -O /dev/null http://localhost:3000 && nslookup google.com localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  config:
  work:
networks:
  default:
  frontend:
    external: true
