- name: Create folder for docker-compose files.
  ansible.builtin.file:
    path: "~/docker-compose/obsidian"
    state: directory
    recurse: true
    mode: "0700"

- name: Generate docker-compose.yml.
  ansible.builtin.template:
    src: "docker-compose.yml"
    dest: "~/docker-compose/obsidian/docker-compose.yml"
    mode: "0600"

- name: Generate CouchDB config.
  ansible.builtin.template:
    src: "local.ini"
    dest: "~/docker-compose/obsidian/local.ini"
    mode: "0600"
    owner: "1000"
    group: "1000"

- name: Start containers.
  community.docker.docker_compose:
    project_src: "~/docker-compose/obsidian"
    pull: true

- name: Allow CouchDB over tailscale.
  community.general.ufw:
    rule: allow
    port: "5984"
    proto: "tcp"
    interface: tailscale0
    direction: in
