version: "3.9"
services:
  db:
    container_name: nextcloud_db
    image: "postgres:14"
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: "{{ nextcloud.db.password }}"
      POSTGRES_USER: nextcloud
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: nextcloud
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "db:/var/lib/postgresql/data:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
  cache:
    container_name: nextcloud_cache
    image: "redis:7-alpine"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --raw incr ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
  app:
    container_name: nextcloud_app
    image: "nextcloud:24-apache"
    restart: "unless-stopped"
    depends_on:
      - db
      - cache
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - "app:/var/www/html"
    environment:
      POSTGRES_PASSWORD: "{{ nextcloud.db.password }}"
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_HOST: nextcloud_db
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud.admin.user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud.admin.password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.svc.fkoehler.xyz nextcloud_app"
      # OVERWRITEWEBROOT: "/nextcloud"
      OVERWRITEHOST: "nextcloud.svc.fkoehler.xyz"
      OVERWRITEPROTOCOL: "https"
      REDIS_HOST: nextcloud_cache
    networks:
      - frontend
      - default
  cron:
    container_name: nextcloud_cron
    image: "nextcloud:24-apache"
    restart: "unless-stopped"
    depends_on:
      - db
      - cache
    entrypoint: /cron.sh
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - "app:/var/www/html"
volumes:
  db:
  app:
networks:
  default:
  frontend:
    external: true