version: "3.9"
services:
  db:
    container_name: nextcloud_db
    image: "postgres:14.6"
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: "{{ nextcloud.db.password }}"
      POSTGRES_USER: nextcloud
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: nextcloud
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nextcloud" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "db:/var/lib/postgresql/data:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
  cache:
    container_name: nextcloud_cache
    image: "redis:7-alpine"
    restart: "unless-stopped"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli --raw incr ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
  app:
    container_name: nextcloud_app
    image: "nextcloud:25.0.3-apache"
    restart: "unless-stopped"
    depends_on:
      - db
      - cache
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - "app:/var/www/html"
    environment:
      POSTGRES_PASSWORD: "{{ nextcloud.db.password }}"
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_HOST: nextcloud_db
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud.admin.user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud.admin.password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud_app"
      # OVERWRITEWEBROOT: "/nextcloud"
      OVERWRITEHOST: "{{ tailscale_ip }}:8001"
      OVERWRITEPROTOCOL: "http"
      REDIS_HOST: nextcloud_cache
    ports:
      - "{{ tailscale_ip }}:8001:80/tcp"
  cron:
    container_name: nextcloud_cron
    image: "nextcloud:25.0.3-apache"
    restart: "unless-stopped"
    depends_on:
      - db
      - cache
    entrypoint: /cron.sh
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - "app:/var/www/html"
  proxy:
    container_name: nextcloud_proxy
    image: "nginx:1.23.3-alpine"
    restart: "unless-stopped"
    depends_on:
      - app
    ports:
      - "{{ tailscale_ip }}:4431:443/tcp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
volumes:
  db:
  app:
