version: "3.9"
services:
  db:
    container_name: nextcloud_db
    image: "postgres:15.3"
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: "{{ nextcloud.db.password }}"
      POSTGRES_USER: nextcloud
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: nextcloud
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nextcloud" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "db:/var/lib/postgresql/data:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
  app:
    container_name: nextcloud_app
    image: "nextcloud:26.0.1-apache"
    restart: "unless-stopped"
    depends_on:
      - db
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - "app:/var/www/html"
    environment:
      POSTGRES_PASSWORD: "{{ nextcloud.db.password }}"
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_HOST: nextcloud_db
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud.admin.user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud.admin.password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.vps.fkoehler.org"
      # OVERWRITEWEBROOT: "/nextcloud"
      OVERWRITEHOST: "nextcloud.vps.fkoehler.org"
      OVERWRITEPROTOCOL: "https"
    ports:
      - "8001:80/tcp"
  cron:
    container_name: nextcloud_cron
    image: "nextcloud:26.0.1-apache"
    restart: "unless-stopped"
    depends_on:
      - db
    entrypoint: /cron.sh
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - "app:/var/www/html"
volumes:
  db:
  app:
