- name: Create folder for docker-compose files.
  ansible.builtin.file:
    path: "~/docker-compose/uptime"
    state: directory
    recurse: true
    mode: "0700"

- name: Generate docker-compose file.
  ansible.builtin.template:
    src: docker-compose.yml
    dest: ~/docker-compose/uptime/docker-compose.yml
    mode: "0700"
  notify:
    - Restart frontend.

- name: Start containers.
  community.docker.docker_compose:
    project_src: "~/docker-compose/uptime"
    pull: true
  notify:
    - Restart frontend.
