version: "3.9"
services:
  app:
    container_name: "uptime_app"
    image: "louislam/uptime-kuma:1.16.1-alpine"
    restart: "unless-stopped"
    volumes:
      - "app:/app/data"
    networks:
      - default
      - frontend
volumes:
  app:
networks:
  default:
  frontend:
    external: true