version: "3.9"
services:
  app:
    container_name: "uptime_app"
    image: "louislam/uptime-kuma:1.17.1-alpine"
    restart: "unless-stopped"
    volumes:
      - "app:/app/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
    networks:
      - default
      - frontend
volumes:
  app:
networks:
  default:
  frontend:
    external: true