version: "3.9"
services:
  livesync:
    container_name: obsidian_livesync
    image: docker.io/couchdb:3.3.3
    restart: unless-stopped
    user: 1000:1000
    environment:
      - COUCHDB_USER={{ obsidian_livesync_user }}
      - COUCHDB_PASSWORD={{ obsidian_livesync_password }}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini:ro
    ports:
      - "{{ tailscale_ip }}:5984:5984"
volumes:
  data: