version: "3.9"
services:
  db:
    image: "postgres:14"
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: "{{ headscale_db_password }}"
      POSTGRES_USER: headscale
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: headscale
    volumes:
      - "db:/var/lib/postgresql/data:rw"
  app:
    image: "headscale/headscale:0.14-alpine"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./headscale.yaml:/etc/headscale/config.yaml:ro"
      - "app:/var/lib/headscale:rw"
    command: headscale serve
    depends_on:
      - db
  proxy:
    image: "nginx:latest"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./dhparams.pem:/etc/nginx/dhparams.pem:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./privkey.pem:/etc/nginx/privkey.pem:ro"
      - "./fullchain.pem:/etc/nginx/fullchain.pem:ro"
      - "./chain.pem:/etc/nginx/chain.pem:ro"
      - "./cert.pem:/etc/nginx/cert.pem:ro"
    ports:
      - 443:443
    depends_on:
      - app
volumes:
  db:
  app:
