version: "3.9"
services:
  app:
    container_name: frontend_app
    image: "nginx:latest"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./dhparams.pem:/etc/nginx/dhparams.pem:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./privkey.pem:/etc/nginx/privkey.pem:ro"
      - "./fullchain.pem:/etc/nginx/fullchain.pem:ro"
      - "./chain.pem:/etc/nginx/chain.pem:ro"
      - "./cert.pem:/etc/nginx/cert.pem:ro"
    ports:
      - "{{ vpn_ipv4.vps }}:80:80"
      - "{{ vpn_ipv4.vps }}:443:443"
    networks:
      - frontend
networks:
  frontend:
    external: true