version: "3.9"
services:
  app:
    container_name: frontend_app
    image: "nginx:1.23.0-alpine"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - "./dhparams.pem:/etc/nginx/dhparams.pem:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./ssl.conf:/etc/nginx/ssl.conf:ro"
      - "./proxy.conf:/etc/nginx/proxy.conf:ro"
      - "./privkey.pem:/etc/nginx/privkey.pem:ro"
      - "./fullchain.pem:/etc/nginx/fullchain.pem:ro"
      - "./chain.pem:/etc/nginx/chain.pem:ro"
      - "./cert.pem:/etc/nginx/cert.pem:ro"
      - "./sites:/etc/nginx/sites"
    ports:
      - "{{ vpn.vps.ipv4 }}:80:80"
      - "{{ vpn.vps.ipv4 }}:443:443"
    networks:
      - default
      - frontend
networks:
  default:
  frontend:
    external: true