- name: Copy systemd-resolved config.
  ansible.builtin.copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart systemd-resolved.

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers

- name: Symlink resolve.conf.
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    force: true
    state: link
    owner: root
    group: root
    mode: "0644"

- name: Create folder for pihole files.
  ansible.builtin.file:
    path: "~/docker-compose/pihole"
    state: directory
    recurse: true
    mode: "0700"

- name: Copy custom Dockerfile.
  ansible.builtin.copy:
    src: pihole-unbound
    dest: "~/docker-compose/pihole/"

- name: Generate docker-compose file.
  ansible.builtin.template:
    src: docker-compose.yml
    dest: ~/docker-compose/pihole/docker-compose.yml
    mode: "0600"

- name: Start containers.
  community.docker.docker_compose:
    project_src: "~/docker-compose/pihole"
    pull: true
    build: true

- name: Allow DNS over tailscale.
  community.general.ufw:
    rule: allow
    port: 53
    proto: "{{ proto }}"
    interface: tailscale0
    direction: in
  loop_control:
    loop_var: proto
  loop:
    - tcp
    - udp

- name: Generate nginx config.
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/sites/pihole.conf
    mode: "0600"
  notify:
    - Restart proxy.
